spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
        use_nationalized_character_data: true
    open-in-view: false
    generate-ddl: true
  session:
    jdbc:
      initialize-schema: always
  threads:
    virtual:
      enabled: true
  datasource:
    url: 'jdbc:mysql://localhost/jxj2?createDatabaseIfNotExist=true&autoReconnect=true&serverTimezone=Asia/Shanghai'
    username: 'jxj'
    password: 'jxj'
server:
  error:
    include-message: always
    include-binding-errors: always
logging:
  charset:
    file: UTF-8
